export const orgsemissores = [
    { value: "SSP", label: "SSP - Serviço de Segurança Pública" },
    // { value: "SSP/AC", label: "SSP/AC - Secretaria de Segurança Pública do Acre" },
    // { value: "SSP/AL", label: "SSP/AL - Secretaria de Segurança Pública de Alagoas" },
    // { value: "SSP/AP", label: "SSP/AP - Secretaria de Segurança Pública do Amapá" },
    // { value: "SSP/AM", label: "SSP/AM - Secretaria de Segurança Pública do Amazonas" },
    // { value: "SSP/BA", label: "SSP/BA - Secretaria de Segurança Pública da Bahia" },
    // { value: "SSPDS/CE", label: "SSPDS/CE - Secretaria de Segurança Pública e Defesa Social do Ceará" },
    // { value: "SSP/DF", label: "SSP/DF - Secretaria de Segurança Pública do Distrito Federal" },
    // { value: "SESP/ES", label: "SESP/ES - Secretaria de Estado da Segurança Pública do Espírito Santo" },
    // { value: "SSP/GO", label: "SSP/GO - Secretaria de Segurança Pública de Goiás" },
    // { value: "SSP/MA", label: "SSP/MA - Secretaria de Segurança Pública do Maranhão" },
    // { value: "SSP/MT", label: "SSP/MT - Secretaria de Segurança Pública do Mato Grosso" },
    // { value: "SSP/MS", label: "SSP/MS - Secretaria de Segurança Pública do Mato Grosso do Sul" },
    // { value: "SSP/MG", label: "SSP/MG - Secretaria de Segurança Pública de Minas Gerais" },
    // { value: "SSP/PA", label: "SSP/PA - Secretaria de Segurança Pública do Pará" },
    // { value: "SSP/PB", label: "SSP/PB - Secretaria de Segurança Pública da Paraíba" },
    // { value: "SSP/PR", label: "SSP/PR - Secretaria de Segurança Pública do Paraná" },
    // { value: "SSP/PE", label: "SSP/PE - Secretaria de Segurança Pública de Pernambuco" },
    // { value: "SSP/PI", label: "SSP/PI - Secretaria de Segurança Pública do Piauí" },
    // { value: "SSP/RJ", label: "SSP/RJ - Secretaria de Segurança Pública do Rio de Janeiro" },
    // { value: "SESED/RN", label: "SESED/RN - Secretaria de Estado da Segurança Pública e da Defesa Social do Rio Grande do Norte" },
    // { value: "SSP/RS", label: "SSP/RS - Secretaria de Segurança Pública do Rio Grande do Sul" },
    // { value: "SESDEC/RO", label: "SESDEC/RO - Secretaria de Estado da Segurança, Defesa e Cidadania de Rondônia" },
    // { value: "SESP/RR", label: "SESP/RR - Secretaria de Segurança Pública de Roraima" },
    // { value: "SSP/SC", label: "SSP/SC - Secretaria de Segurança Pública de Santa Catarina" },
    // { value: "SSP/SP", label: "SSP/SP - Secretaria de Segurança Pública de São Paulo" },
    // { value: "SSP/SE", label: "SSP/SE - Secretaria de Segurança Pública de Sergipe" },
    // { value: "SSP/TO", label: "SSP/TO - Secretaria de Segurança Pública do Tocantins" },
    // { value: "PF", label: "PF - Polícia Federal" },
    // { value: "PM", label: "PM - Polícia Militar" },
    // { value: "CBM", label: "CBM - Corpo de Bombeiros Militar" },
    // { value: "DETRAN", label: "DETRAN - Departamento Estadual de Trânsito" },
    // { value: "MAER", label: "MAER - Ministério da Aeronáutica" },
    // { value: "MB", label: "MB - Marinha do Brasil" },
    // { value: "II", label: "II - Instituto de Identificação" },
    // { value: "PCE", label: "PCE - Polícia Civil do Estado" },
    // { value: "MS", label: "MS - Ministério da Saúde" },
    // { value: "MC", label: "MC - Ministério da Cidadania" },
    // { value: "CARTORIO", label: "CARTORIO - Cartório de Registro Civil" },
    // { value: "other", label: "other - Outro órgão não listado" }
]
