export const statesBR = [
    { value: "SP", label: "São Paulo" },
    { value: "RJ", label: "Rio de Janeiro" },
    { value: "MG", label: "Minas Gerais" },
    { value: "ES", label: "Espírito Santo" },
    { value: "PR", label: "Paraná" },
    { value: "RS", label: "Rio Grande do Sul" },

    { value: "SC", label: "Santa Catarina" },
    { value: "GO", label: "Goiás" },
    { value: "MT", label: "Mato Grosso" },
    { value: "MS", label: "Mato Grosso do Sul" },
    { value: "AC", label: "Acre" },
    { value: "AL", label: "Alagoas" },
    { value: "AP", label: "Amapá" },
    { value: "AM", label: "Amazonas" },
    { value: "BA", label: "Bahia" },
    { value: "CE", label: "Ceará" },
    { value: "DF", label: "Distrito Federal" },
    { value: "MA", label: "Maranhão" },
    { value: "PB", label: "Paraíba" },
    { value: "PE", label: "Pernambuco" },
    { value: "PI", label: "Piauí" },
    { value: "RN", label: "Rio Grande do Norte" },
    { value: "RO", label: "Rondônia" },
    { value: "RR", label: "Roraima" },
    { value: "SE", label: "Sergipe" },
    { value: "TO", label: "Tocantins" },
];
